import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import style from './mainpage.module.css';

import Header from '@/app/(afterAuth)/_component/Header';
import RecommendsFollower from './(afterAuth)/_component/RecommendsFollower';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const loginState = true;

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  // {/* TODO: 로그인 여부에 따라 분기 처리 */}
  return (
      <html lang='en'>
      <body className={`${inter.className} ${loginState ? style.login : style['non-login']}`}>
      <main className={`${style.container} ${loginState ? style.login : style['non-login']} `}>
        {loginState && <Header/>}
        <div className={style['main-section']}>{children}</div>
        <div id='portal'></div>
      </main>
      </body>
      </html>
  );
}
