import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import style from './mainpage.module.css';

import Header from '@/app/(afterAuth)/_component/Header';
import RecommendsFollower from './(afterAuth)/_component/RecommendsFollower';
import {ReactNode} from "react";
import {auth} from "@/app/api/auth/[...nextauth]/route";
import AuthSession from "@/app/_provider/AuthSession";
import MSWComponent from "@/app/_component/MSWComponent";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default async function RootLayout({
                                           children,
                                         }: {
  children: ReactNode;
}) {
  return (
      <html lang='en'>
      <body className={`${inter.className}`}>
      <MSWComponent/>
      <AuthSession>
        {children}
      </AuthSession>
      <div id='portal'></div>
      </body>
      </html>
  );
}
