import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import AuthSession from '@/app/_provider/AuthSession';
import MSWComponent from '@/app/_component/MSWComponent';
import DecisionLogin from './_component/DecisionLogin';
import { auth } from '@/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await auth();
  
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <MSWComponent />
        <AuthSession>
          <DecisionLogin session={session}>
            {children}
          </DecisionLogin>
        </AuthSession>
        <div id='portal'></div>
      </body>
    </html>
  );
}
